### ISSUE TITLE
Add Events on Mozilla Study Group Events

### ISSUE THREAD

**Issue by WW-Web-Infra** [mozillascience/studyGroupEvents#5]
There are many [Study Groups](https://github.com/AnamikaD/studyGroup) around the world. We can collect all the events and display [here](https://mozillascience.github.io/studyGroupEvents/)!!

**Comment by HassenPy** [comment]
hmm, can you elaborate on this?

**Comment by WW-Web-Infra** [comment]
@HassenPy if you see study group, you can create your own website and host events!! So why not post your events on Mozilla study group event so that everyone can view your events! I hope that makes sense?

**Comment by HassenPy** [comment]
understood.

**Comment by HassenPy** [comment]
i think i ll be working on this for the global sprint.

**Comment by WW-Web-Infra** [comment]
@great!! Let's get started!!

**Comment by HassenPy** [comment]
we'll be using the global sprint gitter channel or is there some other channel?
p.s: i'm going to sleep now :laughing:

**Comment by WW-Web-Infra** [comment]
@HassenPy go to sleep we will meet tomorrow morning!! Yes we can user the global sprint gitter or you can message me or Aurelia on gitter!!
